# Generated by Django 3.2.10 on 2021-12-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('first_address', models.CharField(max_length=1024)),
                ('second_address', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(help_text='Enter Contact Number', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='artimages/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('section', models.TextField()),
                ('written_by', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('written_by', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=1024)),
                ('section', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('objective', models.CharField(max_length=1024)),
                ('topics', models.CharField(max_length=1024)),
                ('methodology', models.CharField(max_length=1024)),
                ('aim', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phno', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1054)),
                ('pic', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('by_name', models.CharField(max_length=1024)),
                ('by_place', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('thumbnail', models.ImageField(upload_to='vimages/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='teams/')),
                ('name', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('fb_link', models.URLField(max_length=1000, null=True)),
                ('linkdin_link', models.URLField(max_length=1000, null=True)),
                ('twitt_link', models.URLField(max_length=1000, null=True)),
                ('fb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Facebook', to='morris_python.social_media', verbose_name='Facebook')),
                ('linkdin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Linkdin', to='morris_python.social_media', verbose_name='Linkdin')),
                ('twitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Twitter', to='morris_python.social_media', verbose_name='Twitter')),
            ],
        ),
    ]
