# Generated by Django 3.2.10 on 2022-02-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('first_line', models.CharField(max_length=1024)),
                ('second_line', models.CharField(max_length=1024)),
                ('third_line', models.CharField(blank=True, max_length=1024)),
                ('fourth_line', models.CharField(blank=True, max_length=1024)),
                ('fifth_line', models.CharField(blank=True, max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('contact1', models.CharField(help_text='Enter Contact Number', max_length=10)),
                ('contact2', models.CharField(blank=True, help_text='Enter Contact Number', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('section', models.TextField()),
                ('written_by', models.CharField(max_length=1024)),
                ('written_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('written_by', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phno', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1054)),
                ('pic', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='teams/')),
                ('name', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('by_name', models.CharField(max_length=1024)),
                ('by_place', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('thumbnail', models.ImageField(upload_to='vimages/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=1024, null=True)),
                ('intro', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('objective', models.CharField(max_length=1024, null=True)),
                ('methodology', models.CharField(max_length=1024, null=True)),
                ('aim', models.CharField(max_length=1024, null=True)),
                ('rythm_of_english', models.CharField(max_length=1024, null=True)),
                ('teching_platform', models.CharField(max_length=1024, null=True)),
                ('duration', models.CharField(max_length=1024, null=True)),
                ('num_of_class', models.IntegerField(null=True)),
                ('topics', models.ManyToManyField(null=True, to='morris_python.topic')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
    ]
