# Generated by Django 3.2.10 on 2022-02-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morris_python', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkdin_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitt_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
    ]
