# Generated by Django 3.2.10 on 2022-02-09 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('morris_python', '0002_auto_20220209_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='written_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
