# Generated by Django 3.2.10 on 2022-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morris_python', '0002_auto_20220112_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_class',
            field=models.IntegerField(null=True),
        ),
    ]
