# Generated by Django 3.2.10 on 2022-04-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morris_python', '0002_auto_20220221_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
        migrations.DeleteModel(
            name='social_media',
        ),
    ]
