# Generated by Django 3.2.10 on 2022-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morris_python', '0003_article_written_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
